[[redirects]]
  from = "/"
  to = "/aboutMe.html"
  status = 200

[[redirects]]
  from = "/work.html"
  to = "/work.html"
  status = 200

[[redirects]]
  from = "/top3Work.html"
  to = "/top3Work.html"
  status = 200

[[redirects]]
  from = "/study.html"
  to = "/study.html"
  status = 200

[[redirects]]
  from = "/projects.html"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/contact.html"
  to = "/contact.html"
  status = 200
